settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: gin-hot-reload
  path: .
  args:
  - -alsologtostderr
  commands:
    install:
      method: swag init -g web_api/main.go -o web_api/docs
      status: true
    build:
      method: go build -tags=jsoniter -o web_api/.bin/main ./web_api/main.go
      status: true
    run:
      method: ./web_api/.bin/main
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
